{{- if .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "service-core.fullname" . }}-secrets'
  namespace: {{ include "service-core.namespace" . }}
  labels:
    {{- include "service-core.labels" . | nindent 4 }}
    {{- if .Values.global.labels }}
      {{- toYaml .Values.global.labels | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  {{- with .Values.secrets -}}
  {{ toYaml . | nindent 2 }}
  {{- end -}}
{{ end -}}
