apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- include "platform-core.labels" . | nindent 4 }}
    {{- with .Values.podSecurityStandards }}
      {{- toYaml . | nindent 4 }}
    {{- end }}